import { Montserrat_Alternates } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const montserratAlternates = Montserrat_Alternates({
  weight: ['400', '700'], // Anda bisa memilih berbagai macam weight
  subsets: ['latin'], // Memilih subset karakter
});

export const metadata = {
  title: "Podcast",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserratAlternates.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
